#!/bin/bash
set -e

# 将环境变量转换为 Wrangler 的本地变量文件 (.dev.vars)
echo "# Auto-generated by docker-entrypoint.sh" > .dev.vars

# 1. 处理必填项 EPG_URL
if [ -z "$EPG_URL" ]; then
    echo "Error: EPG_URL environment variable is required."
    exit 1
else
    echo "EPG_URL=\"$EPG_URL\"" >> .dev.vars
fi

# 2. 处理可选项
if [ -n "$EPG_URL_BACKUP" ]; then
    echo "EPG_URL_BACKUP=\"$EPG_URL_BACKUP\"" >> .dev.vars
fi

if [ -n "$CACHE_TTL" ]; then
    echo "CACHE_TTL=\"$CACHE_TTL\"" >> .dev.vars
fi

echo "✅ Environment configured. Starting Worker..."

# 执行传入的命令 (即 Dockerfile 中的 CMD)
exec "$@"